version: "3"
services:
  mspproxy2:
    container_name: mspproxy2
    image: jwilder/nginx-proxy:latest
    ports:
      - "80:80"
      - "443:443"      
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./web/vhosts.d/:/etc/nginx/conf.d
    links:
      - mspweb2
    networks:
      - msp-network2
  mspmysql:
    container_name: mspmysql
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: msp
    volumes:
      - ./data/db:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"      
    expose:
      - 3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: msp
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
    networks:
      - msp-network2 
  mspweb2:
    container_name: mspweb2
    command: npm run start
    build: ./client
    volumes:
      - ./client:/usr/src/app
    environment:
      VIRTUAL_HOST: ledger.local.mspfamilylending.com
    expose:
      - 5000
    links:
      - mspmysql
    depends_on:
      - mspmysql
    tty: true
    networks:
        - msp-network2
networks:
    msp-network2:
        driver: bridge
