version: "3"
services:
  mspproxy2:
    container_name: mspproxy2
    image: jwilder/nginx-proxy:latest
    ports:
      - "80:80"
      - "443:443"      
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./web/vhosts.d/:/etc/nginx/conf.d
    links:
      - mspweb2
    networks:
      - msp-network2
  mspmongo:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/bitnami 
  mspweb2:
    container_name: mspweb2
    command: npm run start
    build: ./client
    volumes:
      - ./client:/usr/src/app
    environment:
      VIRTUAL_HOST: ledger.local.mspfamilylending.com
    expose:
      - 5000
    links:
      - mspmongo
    depends_on:
      - mspmongo
    tty: true
    networks:
        - msp-network2
networks:
    msp-network2:
        driver: bridge
